# Generated by Django 5.0.4 on 2024-04-18 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationForm_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('no_results_text', models.CharField(max_length=100)),
                ('link_text', models.CharField(max_length=100)),
                ('crawl_button_text', models.CharField(max_length=100)),
                ('search_button_text', models.CharField(max_length=100)),
                ('page_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccomodationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=4)),
                ('link', models.URLField(max_length=300)),
                ('img_src1', models.TextField(null=True)),
                ('img_src2', models.TextField(null=True)),
                ('img_src3', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chinese_food_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='japanese_food_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='korean_food_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=300)),
                ('business_hours', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='western_food_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='GyeongJu.shop')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionExperienceInfo',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('info', models.CharField(default='', max_length=300)),
                ('call', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('homepage', models.URLField(default='', max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GyeongJu.typeinfo')),
            ],
        ),
    ]
